### ISSUE TITLE
doesn't converge on test problem

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#102]
From "Solver test":

```jl
x = Convex.Variable(1,:Int)
y = Convex.Variable(1)

problem = Convex.minimize(-3x - y,
                      x >= 1,
                      y >= 0,
                      3x + 2y <= 10,
                      x^2 <= 5,
                      exp(y) + x <= 7)

Convex.solve!(problem, PajaritoSolver(log_level=1,mip_solver_drives=false,mip_solver=GurobiSolver(), cont_solver=ECOSSolver()))
```
gives
```
Finished iterative outer approximation algorithm:
 - Total time (s)       =       2.84e+00
 - Status               =     Suboptimal
 - Best feasible obj.   =  -7.241046e+00
 - Final OA obj. bound  =  -7.619636e+00
 - Relative opt. gap    =      5.228e-02
 - Conic iter. count    =              1
```
There's no reason to not converge on this problem, there's a bug somewhere. Using the NLP algorithm with Ipopt, the optimal value is -7.60944.

**Comment by chriscoey** [comment]
Have you tried changing some parameters eg cut projections to get some
insight as to what causes it to cycle?

**Comment by mlubin** [comment]
The first-order issue isn't with cuts. Pajarito gives the correct assignment of the integer variable, so there's something wrong with the subproblem.

**Comment by mlubin** [comment]
It's ECOS or ECOS.jl. SCS works fine.

**Comment by chriscoey** [comment]
DAM RIGHT IT IS

**Comment by mlubin** [comment]
All of the unit tests now return optimal status after https://github.com/mlubin/Pajarito.jl/pull/100 and https://github.com/JuliaOpt/ECOS.jl/pull/46

**Comment by chriscoey** [comment]
great! now onto MICPExperiments?

**Comment by mlubin** [comment]
Closed by https://github.com/mlubin/Pajarito.jl/pull/104
