### ISSUE TITLE
support variables in zero cones

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#105]
Some of the cblib instances have these. Would be nice for them to work without any preprocessing.

**Comment by chriscoey** [comment]
OK latest PR #117 should do this, but needs to be tested on larger problems

**Comment by chriscoey** [comment]
@mlubin so I added a zero cone test on a small SOC problem. But it didn't pass the tests - it comes back suboptimal. Given how small and "easy" the example is, this shouldn't happen. Do you have any ideas why?
