### ISSUE TITLE
return gracefully when the conic solver fails

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#108]
At https://github.com/mlubin/Pajarito.jl/blob/157dbda1291f4a04301c83f65572c0e05ec05bf2/src/conic_algorithm.jl#L963 we throw an error if the conic solver returns a weird status. We should return an error status from Pajarito instead of throwing an error and crashing code.

**Comment by chriscoey** [comment]
@mlubin can you give an example of how to do this?

**Comment by chriscoey** [comment]
it's currently named `:ConicFailure` in PR #140

**Comment by chriscoey** [comment]
closed by #140
