### ISSUE TITLE
tweak gap logic

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#114]
``m.gap_rel_opt = abs(m.obj_mip - m.obj_best) / (abs(m.obj_best) + 1e-5)``
If minimizing and ``m.obj_best`` is less than ``m.obj_mip``, then the gap should be zero, not positive.

**Comment by chriscoey** [comment]
could be ok to be negative, just gives more information

**Comment by chriscoey** [comment]
make it 
`m.gap_rel_opt =(m.obj_best - m.obj_mip) / (abs(m.obj_best) + 1e-5)
`

**Comment by chriscoey** [comment]
see PR #122

**Comment by mlubin** [comment]
You should just reference the corresponding issue from the PR.

**Comment by chriscoey** [comment]
fixed in #122
