### ISSUE TITLE
heuristic solutions in mip solver driven algorithm

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#124]
currently we create a queue and add to it every time we get a better feasible solution. but this queue leads to somewhat complicated code. why don't we just keep only one, best, feasible solution? can it help at all to add more than one solution, even if only one is best?

**Comment by chriscoey** [comment]
the code would be simplified significantly by using only the best feasible solution

**Comment by mlubin** [comment]
There's no reason to send anything other than the best one

**Comment by chriscoey** [comment]
only using best one now
