### ISSUE TITLE
in solver-driven alg, in some tests, seems to be thousands of identical conic subproblem calls

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#128]
I just ran `sssd-strong-25-8` for example and had thousands of subproblem calls all with the same output. Is this a bug in solver-driven?

**Comment by mlubin** [comment]
None of the solvers guarantee that you won't be called twice with the same
integer solution. We may want to keep the cuts around if this happens
frequently.

**Comment by mlubin** [comment]
https://www.gurobi.com/documentation/6.5/refman/cs_grbcallback_addlazy.html

"Your callback should be prepared to cut off solutions that violate any of your lazy constraints, including those that have already been added. Node solutions will usually respect previously added lazy constraints, but not always."

**Comment by chriscoey** [comment]
hm. so what should we do? In some cases MSD alg seemed to work well. On
this one, it was terribly inefficient perhaps for this reason.

**Comment by chriscoey** [comment]
OK so fixed the bug where I was giving the same best feasible solution to the MSD mip solver multiple times. But still have the same behavior of many identical conic subproblem calls. Perhaps the issue is peculiar to Gurobi - will try with CPLEX once I install (having problems with cplex.jl).
