### ISSUE TITLE
stop MIPs early feature

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#129]
maybe just have two options:
- every n MIP solves, go to optimality
- in between, solve for T seconds and then stop

**Comment by chriscoey** [comment]
if the MIP solver finishes with `:UserLimit` then the objective is not a valid OA bound. What do we have to keep track of and test in terms of integer solutions, to ensure convergence? We don't have to keep ALL previous integer solutions do we? Is just the most recent one good enough?

**Comment by mlubin** [comment]
http://mathprogbasejl.readthedocs.io/en/latest/solverinterface.html#getobjbound should give you a valid bound if it's implemented

**Comment by chriscoey** [comment]
what about the integer solutions, which may repeat? how should we manage those?

**Comment by mlubin** [comment]
What do the integer solutions have to do with convergence?

**Comment by chriscoey** [comment]
I'm saying how do we avoid solving the same conic subproblem twice and
adding the same cuts?

**Comment by mlubin** [comment]
Keep a list of integer solutions we've seen.

**Comment by chriscoey** [comment]
Check every new integer solution against every old one?

**Comment by chriscoey** [comment]
what if i tried hashing every integer solution and just make sure the hash value hasn't been seen before. can you think of a smarter way?

**Comment by chriscoey** [comment]
or what about using a Set type to store all the integer solutions, then Julia would hash it to check if it's in the set, right? is that the best way?

**Comment by mlubin** [comment]
There's no real need to worry about the storage here but hashing is also
correct.

**Comment by chriscoey** [comment]
ok i'll hash new integer vectors, put the value in a set, and for later solutions, just check membership in the set

**Comment by mlubin** [comment]
You should just use a set of vectors of integer solutions. No need to manually hash.

**Comment by chriscoey** [comment]
But if there are thousands of iterations with early mip stop then we are
storing thousands of vectors we don't actually need

**Comment by mlubin** [comment]
That's dominated by the storage already being used for cuts corresponding to each integer solution.

**Comment by chriscoey** [comment]
By the MIP solver, right? There no reason for us to store cuts

**Comment by mlubin** [comment]
Correct.

**Comment by chriscoey** [comment]
Should be fixed in #138.

But I've been thinking: maybe instead of giving a time limit, what we want is an option for it to solve for a fixed fraction of the most recent zero gap MIP solve time.

That way, you don't need to know how hard the problem is ahead of time. You just say "I want to solve up to 4 early stop problems between each full solve, and i want to stop the MIPs when they are each 1/4 the time taken by the last full solve". @mlubin, thoughts? It would require less tuning.

**Comment by mlubin** [comment]
It makes sense but we don't have a solver-independent option for that.

**Comment by chriscoey** [comment]
It's still just a time limit. Just pass in a time that is the right fraction of the time we logged for the last full MIP solves.

**Comment by chriscoey** [comment]
OK per offline discussion we may want both this and a Cbc-specific gap option

**Comment by chriscoey** [comment]
OK going with new idea: pass in option for number of suboptimal solves between full solves, and pass in extra MIP solver for suboptimal MIP solves (gap or time limit options can be set on that solver directly)

**Comment by chriscoey** [comment]
resolved by PR #141
