### ISSUE TITLE
conic failure in MSD

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#145]
If we [terminate](https://github.com/mlubin/Pajarito.jl/blob/730f976cc0caa98577852e8d6d81bf4f8d29334b/src/conic_algorithm.jl#L1122) the mip solver because of conic failure, Pajarito should return ``:ConicFailure`` instead of ``:UserLimit``.

**Comment by chriscoey** [comment]
closed by #146

**Comment by chriscoey** [comment]
closed by #147
