### ISSUE TITLE
document all public options

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#16]
1. Decide which solver options we want to officially support. It's okay to have a few internal options.
2. Document them in README.md

**Comment by emreyamangil** [comment]
Will do! Tomorrow I will start writing a detailed readme as well! (house of cards interference :))

**Comment by chriscoey** [comment]
solver options updated. they have short descriptions next to where they are defined in solver.jl

**Comment by mlubin** [comment]
The descriptions in the readme should also be updated.

**Comment by chriscoey** [comment]
done
