### ISSUE TITLE
add unit test for first mip returning UserLimit

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#162]
This corner case seemed to uncover a lot of small issues (https://github.com/mlubin/Pajarito.jl/pull/161 https://github.com/mlubin/Pajarito.jl/pull/160) not currently covered by our tests.

**Comment by chriscoey** [comment]
@mlubin what do you suggest? a problem that is large, with a small time limit?

**Comment by mlubin** [comment]
Yep

**Comment by chriscoey** [comment]
ok i now do a timeout test on the same problem, larger, using MISOCP outer, so the first mip solve will be slow
