### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#18]
Pajarito has 80% code coverage on the tests, which is not bad.

Looking at the report (https://codecov.io/github/mlubin/Pajarito.jl/src/nonlinear.jl?ref=e97766b1df96a1e74e4ce0adaa3294cf5924167a), it seems like we don't run the infeasible NLP code in the tests, can we add a test to cover this?

The coverage for the conic code is better (https://codecov.io/github/mlubin/Pajarito.jl/src/nonlinear.jl?ref=e97766b1df96a1e74e4ce0adaa3294cf5924167a), but there are still some chunks of code which aren't tested.

**Comment by chriscoey** [comment]
@mlubin for conic algorithm, we lose a lot of coverage by not printing any of logging info. maybe we want one test where we use log_level = 3?

**Comment by mlubin** [comment]
Sure, wouldn't hurt.

**Comment by chriscoey** [comment]
@mlubin do we need any tests to improve nonlinear alg code cov? is infeasible NLP code covered now? (I don't know which function you meant in your first comment)

i am improving conic alg code cov

**Comment by chriscoey** [comment]
#279 gives us pretty much maximal conic algorithm coverage

I will close this issue if the issue if there is nothing more to do for nonlinear algorithm coverage

**Comment by mlubin** [comment]
Most of the uncovered lines now are for error handling. You can hack the coverage statistics by changing
```julia
if isempty(inds)
    error("A cone $spec has no associated indices\n")
end
```
into
```julia
isempty(inds) && error("A cone $spec has no associated indices\n")
```
but that's not really needed.

**Comment by chriscoey** [comment]
what about the red around line 136-154
`function MathProgBase.eval_jac_prod(d::InfeasibleNLPEvaluator, y, x, w)`

**Comment by mlubin** [comment]
We don't have any NLP solvers which use that method, so it's hard to test. We could just comment it out until it's needed.

**Comment by chriscoey** [comment]
none exist?

**Comment by chriscoey** [comment]
i will comment it out

**Comment by mlubin** [comment]
They exist in principle but not in any JuliaOpt packages that I'm aware of.

**Comment by mlubin** [comment]
You should also remove ``:JacVec`` from ``features_available``.

**Comment by chriscoey** [comment]
ok will do
