### ISSUE TITLE
Remove DefaultMIPSolver and DefaultConicSolver

### ISSUE THREAD

**Issue by joehuchette** [mlubin/Pajarito.jl#195]
Due to the changes in JuliaOpt/MathProgBase.jl#151, Pajarito doesn't work against MPB master. A workaround is to specify the ``mip_solver``, ``mip_subopt_solver``, and ``cont_solver``, but there's still a usage inside the algorithm that I can't make sense of: https://github.com/mlubin/Pajarito.jl/blob/f2d2c45d007a1dc0fb2eead3f8aaa0b79b37272b/src/conic_algorithm.jl#L260

**Comment by mlubin** [comment]
Don't use Pajarito on MPB master for the time being.

**Comment by joehuchette** [comment]
I'm willing to make a PR if you have an idea how to fix the last usage

**Comment by mlubin** [comment]
That if condition can be removed, that code should run for all solvers.

**Comment by chriscoey** [comment]
closed #240 (using dummy solver in solver.jl)
