### ISSUE TITLE
Remove debugging code from pajarito_feasibility.jl

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#2]
https://github.com/mlubin/Pajarito.jl/blob/7259da06c0af2be2eb6e70ae7d40527e2bd858d6/src/pajarito_feasibility.jl#L123
https://github.com/mlubin/Pajarito.jl/blob/7259da06c0af2be2eb6e70ae7d40527e2bd858d6/src/pajarito_feasibility.jl#L189

These should be removed or turned into options.

**Comment by emreyamangil** [comment]
I think we should just remove pajarito_feasibility as I am not sure if it will work for everything, this was just to test gams01 solution.

**Comment by mlubin** [comment]
What does pajarito_feasibility do exactly?

**Comment by emreyamangil** [comment]
It was just a script to check if the gams01 solution from dcp was feasible with nlp

**Comment by mlubin** [comment]
Ok, let's remove that file for now. If we need to do it in the future we can develop a more general utility.

**Comment by emreyamangil** [comment]
will do!

**Comment by mlubin** [comment]
Already done :)

**Comment by emreyamangil** [comment]
Faster than light! :) Will work on whats left as soon as I get to office, will give you a call 10am!
