### ISSUE TITLE
merge PajaritoConicSolver and PajaritoSolver

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#20]
I think we should merge ``PajaritoConicSolver`` and ``PajaritoSolver``. This way we have a single set of options to document and users don't need to think about which version they're using. We just need to implement:
```
MathProgBase.NonlinearModel(s::PajaritoSolver) = PajaritoNLPModel(...)
MathProgBase.ConicModel(s::PajaritoSolver) = PajaritoConicModel(...)
```
This is one of the reasons why I pushed through the restructuring of the MathProgBase interface in the fall.

**Comment by emreyamangil** [comment]
I see, will look into this asap!
