### ISSUE TITLE
save best solution that is feasible for the MIP solver's tolerances, for warm-starting?

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#200]

**Comment by chriscoey** [comment]
maybe save best solution that is feasible for the MIP solver's tolerances, so can use as a warm-start without being rejected

**Comment by chriscoey** [comment]
a much preferable option is to tell the MIP solver to try to repair any conic solutions that are slightly infeasible for the MIP solver's tolerances

eg for CPLEX, always using level 4 for the [MIP start repair option ](https://www.ibm.com/support/knowledgecenter/SS9UKU_12.7.0/com.ibm.cplex.zos.help/CPLEX/UsrMan/topics/discr_optim/mip/para/49_mipStarts.html)

**Comment by mlubin** [comment]
CPLEX is using level 4 by default. But I don't know if that actually means solving an LP with the fixed integer values.

**Comment by mlubin** [comment]
https://github.com/JuliaOpt/CPLEX.jl/pull/120

**Comment by mlubin** [comment]
CPX_MIPSTART_NOCHECK
