### ISSUE TITLE
add more conic test problems, and test more options

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#204]
in particular we want more tests with SDP (/PSD) cones

i can add experimental design

@mlubin did you suggest plugging into conic benchmark utilities to run a larger swath of tests? that will cover us for second order and exponential cones but not psd cones

**Comment by mlubin** [comment]
I did, but we'd need to register https://github.com/mlubin/ConicBenchmarkUtilities.jl.

**Comment by chriscoey** [comment]
also we have a dearth of general-integer problems in current set of tests

**Comment by chriscoey** [comment]
Any reason not to register ConicBenchmarkUtilities soon?

**Comment by mlubin** [comment]
No, I can tidy it.

**Comment by chriscoey** [comment]
OK awesome thanks

**Comment by chriscoey** [comment]
So this would give us a larger set of tests. Would we pick a selection of fast cblib (SOC, Exp) problems and have these be run (with various options) automatically after the existing tests in runtests.jl? Or should this larger test set be optional?

**Comment by chriscoey** [comment]
Now that ConicBenchmarkUtilities.jl is registered, how do you suggest using it for tests, @mlubin?

**Comment by mlubin** [comment]
commit some CBF files to the test directory and verify that we get correct objective values

**Comment by chriscoey** [comment]
satisfied for now, given codecov reports and the new tests
