### ISSUE TITLE
feasibility of conic solver solutions and 'tol_prim_infeas'

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#207]
decide whether this should always be done or should be optional, and what status to return if we thought we were optimal but we aren't quite feasible for primal inf tolerance.

with refactoring it may be worth using feasibility checks on conic solver solutions (including when ECOS returns suboptimal or Mosek returns stall etc) so that we never take incumbents that aren't feasible for the user's primal inf tol. we test MIP solver solutions for feasibility already but that is slightly cleaner/easier as a byproduct of primal cut functions.

**Comment by chriscoey** [comment]
ideally it would be done at each conic solve. i will try that.

**Comment by mlubin** [comment]
I don't think we should discard any conic solutions that came back when the conic solver returned ``:Optimal``, regardless of feasibility checks.

**Comment by chriscoey** [comment]
then we should discuss the purpose of the primal infeasibility tolerance option

**Comment by mlubin** [comment]
For validating feasibility of solutions that didn't result from an ``:Optimal`` conic solve.

**Comment by chriscoey** [comment]
what is users are using SCS, which as a first order solver may have a poor feasibility tolerance (which could be calculated very differently too). how do we suggest they pick their primal inf tol?

**Comment by mlubin** [comment]
We don't have any guidance for this use case.

**Comment by chriscoey** [comment]
well probably we need some general inf tol guidance either as part of the conic solver section or separately

**Comment by chriscoey** [comment]
possibly the naming of the option itself is misleading

**Comment by chriscoey** [comment]
perhaps it should just be the same as the MIP solver linear tolerance. so we tell users that they should ensure the MIP solver abs feas tol and the prim inf tol are to be set the same. 

there is no function to automatically extract that value from the MIP solver through MPB

**Comment by chriscoey** [comment]
in which case a renaming may be in order

**Comment by chriscoey** [comment]
I think we should discuss this a little more.

**Comment by chriscoey** [comment]
leaving for now unless someone gets confused
