### ISSUE TITLE
mention list of useful solvers on docs?

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#211]
Maybe with suggested options included.

Tests print out the following obvious ones (missing is cbc and scip etc from MIP). Are there any continuous solvers conspicuously missing?

```
MIP solvers:
Gurobi.GurobiSolver(nothing,Any[(:OutputFlag,0),(:Presolve,0)])
CPLEX.CplexSolver(Any[(:CPX_PARAM_PRELINEAR,0),(:CPX_PARAM_PREIND,0),(:CPX_PARAM_ADVIND,0),(:CPX_PARAM_MIPSEARCH,1),(:CPX_PARAM_MIPCBREDLP,0),(:CPX_PARAM_SCRIND,0)])

NLP solvers:
Ipopt.IpoptSolver(Any[(:print_level,0)])

Conic SOC solvers:
ECOS.ECOSSolver(Any[(:verbose,false)])
SCS.SCSSolver(Any[(:eps,1.0e-5),(:max_iters,100000),(:verbose,0)])
Mosek.MosekMathProgSolverInterface.MosekSolver(Any[(:LOG,0)])

Conic Exp+SOC solvers:
ECOS.ECOSSolver(Any[(:verbose,false)])
SCS.SCSSolver(Any[(:eps,1.0e-5),(:max_iters,100000),(:verbose,0)])

Conic SDP+SOC solvers:
SCS.SCSSolver(Any[(:eps,1.0e-5),(:max_iters,100000),(:verbose,0)])
Mosek.MosekMathProgSolverInterface.MosekSolver(Any[(:LOG,0)])
```

**Comment by chriscoey** [comment]
continuous solvers could be in a table with the types of cones they can handle (NLP cannot do PSD)

**Comment by chriscoey** [comment]
@mlubin I think this list of solvers would make it much easier for users to get started, especially if they are less familiar with JuliaOpt

Maybe it would be worthwhile having a new examples folder where can put a few codes (eg exp design), and encourage users to contribute more such example files.

**Comment by mlubin** [comment]
Knitro also works as an NLP solver.

**Comment by chriscoey** [comment]
ok so knitro (for NLP) and GLPK (for MIP) are added to that list. what about SCIP, is it mature enough as a lazy solver package to be able to recommend?

**Comment by mlubin** [comment]
It's okay to list SCIP but we should say MSD is experimental. Cbc should also be listed as an open-source solver.
