### ISSUE TITLE
rescaling of dual from relaxation

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#213]
https://github.com/mlubin/Pajarito.jl/blob/469e50e09354c18e032591b6c0ca7a177eb3542c/src/conic_algorithm.jl#L385
It's unclear why the objective value of the relaxation should show up there. I think the better rescaling is just ``(m.num_soc + m.num_exp + m.num_sdp)``.

**Comment by chriscoey** [comment]
if all the other subproblem cuts are scaled in that way, why shouldn't these ones be?

**Comment by mlubin** [comment]
The other subproblem cuts are rescaled that way to get specific guarantees about termination when we repeat an integer solution. That argument doesn't apply to the relaxation.

**Comment by chriscoey** [comment]
Sure, from a convergence proof standpoint. But I'm not convinced it's worth changing from a practical standpoint. Let's discuss more. Do you have a reason why it could hurt?

**Comment by mlubin** [comment]
No, but it seems arbitrary.

**Comment by chriscoey** [comment]
Ok, to me, the opposite seems arbitrary, because why would we choose to scale it differently from the other subproblem cuts
