### ISSUE TITLE
process initial soc cuts as K* cuts

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#215]

**Comment by chriscoey** [comment]
i tried this, it was too ugly, and it didn't really make sense for the other cones either. only works in special cases. so I think it's best to leave the initial cuts as-is

**Comment by mlubin** [comment]
It actually works for any initial cut we have, it's not a special case. Anyway I'll leave the decision to you.

**Comment by chriscoey** [comment]
Psd initial cuts too?

**Comment by chriscoey** [comment]
If it works for every initial cut for every cone and isn't ugly or inefficient, I'll reconsider

**Comment by chriscoey** [comment]
The problem is we have to be able to pass in one dual and from that all the types of cuts will come, because is how the K* cuts functions work and i don't want to break the nice abstraction

**Comment by mlubin** [comment]
Yes, it works for psd initial cuts, but it's maybe a bit convoluted.

On Feb 18, 2017 1:57 PM, "Chris C." <notifications@github.com> wrote:

Psd initial cuts too?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mlubin/Pajarito.jl/issues/215#issuecomment-280866972>,
or mute the thread

**Comment by chriscoey** [comment]
It doesn't work for SOC because we only add one side of the disaggregated cuts, so we would need to call K* twice in that case. Too ugly. For psd we would need to put together the right matrix etc. 

Leaving as-is.
