### ISSUE TITLE
add hijazi example as unit test

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#216]
check
- initial L1 cuts should require no iterations
- without L1 cuts, disagg needs x many iterations
- without L1 cuts and without disagg, absvalue lifting only needs one cut
etc

can pull out iteration count from m.logs

**Comment by mlubin** [comment]
Disagg should need 2 iterations

**Comment by chriscoey** [comment]
should i just use a 0 objective (feasibility problem)?

**Comment by mlubin** [comment]
Yes, it's a feasibility problem

**Comment by chriscoey** [comment]
see #217
