### ISSUE TITLE
clean zeros in eigenvectors before form projected duals and cuts?

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#231]
this gives us PSD cuts, but we can't easily guarantee much about the smallest epsilon values, unless we do something smart

**Comment by mlubin** [comment]
I'd rather guarantee that we add correct cuts than guarantee that we don't add cuts with certain coefficients, which is a pretty meaningless guarantee.

**Comment by chriscoey** [comment]
then what's the point of ever cleaning zeros?

**Comment by mlubin** [comment]
If we stop doing it, we'll solve fewer problems correctly

**Comment by chriscoey** [comment]
maybe it should be an option. it's only there to help when MIP solvers fail with epsilons. we never tested that with CPLEX.

**Comment by chriscoey** [comment]
I get that it also sparsifies cuts, but we are trying to do too many things disparate things with one function, hence the conflict when it comes to psd cuts

**Comment by chriscoey** [comment]
Clean zeros from sqrt eigenvalue times eigenvector
