### ISSUE TITLE
fix deprecations

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#253]
see travis nightly. eg
`WARNING: Array{T}(::Type{T}, m::Int) is deprecated, use Array{T}(m) instead.`
`WARNING: isnan{T <: Number}(x::AbstractArray{T}) is deprecated, use isnan.(x) instead.`

**Comment by mlubin** [comment]
JuMP isn't free of deprecations yet, but wouldn't hurt to fix the ones here.
