### ISSUE TITLE
add comments for add_cut_sdp!

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#262]
So that SOC cuts can be understood without extra context. The ``V`` argument is mysterious.

**Comment by mlubin** [comment]
The comment:
```
                    # Use norm and transformation from RSOC to SOC
                    # yz >= ||x||^2, y,z >= 0 <==> norm2(2x, y-z) <= y + z
```
is also a bit confusing since everywhere else we use RSOC to mean the version with the 2 in front.

**Comment by chriscoey** [comment]
True, OK. Same in initial sdp soc cuts
