### ISSUE TITLE
test makes JuMP discard internal model?

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#268]
@mlubin  I get 
`WARNING: Solver does not appear to support adding constraints to an existing model. JuMP's internal model will be discarded.
`
from:
```
using Convex, Pajarito, CPLEX, ECOS

x = Convex.Variable(1, :Int)
y = Convex.Variable(1)

problem = Convex.minimize(-3x - y,
                   x >= 1,
                   y >= 0,
                   3x + 2y <= 10,
                   x^2 <= 5,
                   exp(y) + x <= 7)

Convex.solve!(problem, 
    PajaritoSolver(
        mip_solver_drives=false, 
        mip_solver=PajaritoSolver(
            mip_solver=CPLEX.CplexSolver(CPX_PARAM_SCRIND=0, CPX_PARAM_EPINT=1e-8, CPX_PARAM_EPRHS=1e-7, CPX_PARAM_EPGAP=1e-8), 
            cont_solver=ECOS.ECOSSolver(verbose=false), 
            log_level=0, 
            rel_gap=1e-8
            ), 
        cont_solver=ECOS.ECOSSolver(verbose=false), 
        log_level=3, 
        soc_in_mip=true
    )
)

@test problem.status == :Optimal
@test isapprox(x.value, 2.0, atol=TOL)
@test isapprox(y.value, 1.609438, atol=TOL)
```

**Comment by mlubin** [comment]
Pajarito, a recursive MISDP solver™

**Comment by mlubin** [comment]
I think you meant to give the non-recursive version. But this is expected with ``soc_in_mip`` because there's no interface to add linear constraints to an existing conic model (CPLEX wrapped in ``lpqp_to_conic``).

**Comment by chriscoey** [comment]
OK, could that cause a significant slowdown at all?

**Comment by chriscoey** [comment]
and should we do something to avoid the warning if we can't change it?

**Comment by mlubin** [comment]
> OK, could that cause a significant slowdown at all?

No, I wouldn't worry about the matrix generation time for solving an MISOCP.

> and should we do something to avoid the warning if we can't change it?

Open an issue at JuMP? There's no way to disable the warning at the moment.
