### ISSUE TITLE
test failure: SDP+SOC conic MISOCP - Iter, Pajarito (as MISOCP OA solver), Mosek

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#272]
The test for `Init and eig SOC cuts: JuMP.jl A-opt design` came back infeasible (on `Pajarito(GLPK, ECOS)`) or cutsfailure (on `Pajarito(CPLEX,MOSEK)`) when it should have been optimal. 

GLPK was printing `Warning: numerical instability (primal simplex, phase II)`. 
Mosek was printing `MOSEK warning 705: #1 (nearly) zero elements are specified in sparse row ''(8) of matrix 'A'.`

It seems to be caused by the SDP SOC cuts. It may be that because we aren't cleaning zeros after we form the cuts, that we are getting epsilon coefficients between 1e-10 and 1e-20. We could try cleaning larger epsilons from the vectors (like `sqrt(zero_tol)`) but I worry that this would hurt us sometimes.

Here is what I'm seeing on `SDP+SOC conic MISOCP - Iter, Pajarito, SCS` where Pajarito is using CPLEX and MOSEK, for the test `Init SOC cuts: JuMP.jl A-opt design` only
```
MOSEK warning 705: #1 (nearly) zero elements are specified in sparse row ''(8) of matrix 'A'.
MOSEK warning 705: #1 (nearly) zero elements are specified in sparse row ''(13) of matrix 'A'.
MOSEK warning 705: #1 (nearly) zero elements are specified in sparse row ''(8) of matrix 'A'.
MOSEK warning 705: #1 (nearly) zero elements are specified in sparse row ''(13) of matrix 'A'.
WARNING: Conic solver failure: returned status Unknown
WARNING: No violated cuts were added on repeated integer solution (this should not happen: please submit an issue)
WARNING: MIP solver returned status CutsFailure, which Pajarito does not handle (please submit an issue)
Init SOC cuts: JuMP.jl A-opt design: Test Failed
  Expression: solve(aOpt,suppress_warnings=true) == :Optimal
   Evaluated: CutsFailure == Optimal
```

**Comment by chriscoey** [comment]
@mlubin could you try running on your computer and see what you get?

**Comment by chriscoey** [comment]
This problem also failed with `Pajarito(CPLEX, Mosek)` as the MISOCP solver (Pajarito returned CutsFailure, which is now MIPFailure)

**Comment by chriscoey** [comment]
@mlubin could you investigate what might be the issue here? does the A opt Pajarito MISOCP with initial SOC cuts only (no SOC subproblem cuts) fail on some solvers for you? 

if that fails as well as the SOC subproblem cuts, then it tells us that it's not the cuts themselves that are the problem (because SOC initial cuts can't be numerically bad... unless the b-Ax 'slacks' are bad)

**Comment by mlubin** [comment]
I can't reproduce the issue using this set of solvers:
```
cont_solver=MosekSolver(LOG=0)
mip_solver = PajaritoSolver(mip_solver=CplexSolver(CPX_PARAM_SCRIND=0),cont_solver=cont_solver, log_level=0)
```
gives
```
Pajarito MICP solve summary:
 - Total time (s)       =       6.98e+00
 - Status               =        Optimal
 - Best feasible obj.   =  +1.771809e-01
 - OA obj. bound        =  +1.771795e-01
 - Relative opt. gap    =      8.056e-06
```

**Comment by mlubin** [comment]
``Pajarito(GLPK, ECOS)`` also converges

**Comment by chriscoey** [comment]
you got
```
Pajarito MICP solve summary:
 - Total time (s)       =       7.31e+00
 - Status               =     Infeasible
 - Best feasible obj.   =  +1.771809e-01
 - OA obj. bound        =  +1.742244e-01
 - Relative opt. gap    =      1.669e-02
```
something is buggy

**Comment by chriscoey** [comment]
At least part of the issue may have been that V didn't have rank q

Another part seems to be that CPLEX often fails with `CPXMIP_OPTIMAL_INFEAS` status
