### ISSUE TITLE
Negative gaps

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#294]
How about printing
```
- Relative opt. gap    =     -6.114e-06
```
as
```
- Relative opt. gap    =     -6.114e-06*
```
to indicate that something weird may be going on? Do we still report Optimal if there's a very large negative gap?

**Comment by chriscoey** [comment]
we do but I could return an error instead of optimal. is MIPFailure an accurate one?

**Comment by mlubin** [comment]
I don't think ``MIPFailure`` is accurate. A negative gap could also result from us accepting a solution from the conic solver that's a bit infeasible. Maybe just ``Error``? I'd reserve it for cases where the gap is less than `-10*rel_gap`.

**Comment by chriscoey** [comment]
#225 will tell us whether we got the solution from the conic solver or the mip solver. this will help us give a more informative warning/error when we have a negative gap

**Comment by chriscoey** [comment]
so if it is a MIP solver solution, what should we error/warn?

what if it is a conic solver solution?

**Comment by mlubin** [comment]
I don't think we need to provide a detailed interpretation that varies based on where the last solution came from. Report an error status, tell people to double check the conic solver and the MIP solver, and move on.

**Comment by chriscoey** [comment]
I think that's being lazy. I'll look at it when I get to #225
