### ISSUE TITLE
remove dependency on CPLEX

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#3]
https://github.com/mlubin/Pajarito.jl/blob/7259da06c0af2be2eb6e70ae7d40527e2bd858d6/src/Pajarito.jl#L22

Pajarito cannot depend on the CPLEX package by default. It should work for users who only have open-source solvers.

**Comment by emreyamangil** [comment]
This is because of the old code (cone_cb is not depending on any solve right now), I will go over the entire repo and make sure all is current code!
