### ISSUE TITLE
need better printing between iterations

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#31]
The following output is not super informative:
> Optimality Gap: 0.02247865065582623 - 0.014371448212041376 = 0.008107202443784853

Could we please have:
- description of what numbers mean (column names)
- iteration number
- abs gap
- relative gap
- print fewer digits (format nicely)

**Comment by emreyamangil** [comment]
Yupp, I will work on making a prettier output tonight! (This is from 6 months ago when me and Miles were debugging very very manually :))

**Comment by chriscoey** [comment]
Thank you Emre!
