### ISSUE TITLE
dimension mismatch error in sparse matrix multiply

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#33]
Writing my problem in JuMP (rather than convex.jl, and generating extended formulation manually). Got the following error:
> ERROR: LoadError: DimensionMismatch("")
>  in A_mul_B! at sparse/linalg.jl:47
>  in * at linalg/matmul.jl:87
>  in populatelinearmatrix at /Users/chris/.julia/v0.4/Pajarito/src/nonlinear.jl:252
>  in optimize! at /Users/chris/.julia/v0.4/Pajarito/src/nonlinear.jl:380
>  in solvenlp at /Users/chris/.julia/v0.4/JuMP/src/nlp.jl:1219
>  in solve at /Users/chris/.julia/v0.4/JuMP/src/solvers.jl:135
>  in solveGraph at /Users/chris/Dropbox/IsingModels/julia/graph_fullExt.jl:51
>  in include at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in include_from_node1 at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in process_options at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in _start at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
> while loading /Users/chris/Dropbox/IsingModels/julia/graph_fullExt.jl, in expression starting on line 79

The code was as follows (in file graph_fullExt.jl in our Dropbox, Emre):
```
pajarito_solver = PajaritoSolver(
        algorithm="OA",verbose=1,socp_disaggregator=true,time_limit=maxSecs,
        mip_solver=CplexSolver(CPX_PARAM_SCRIND=0,CPX_PARAM_EPINT=1e-8,CPX_PARAM_EPRHS=1e-8,CPX_PARAM_TILIM=60*60*10),
        cont_solver=IpoptSolver(print_level=0))

    mod = Model(solver=pajarito_solver)

    @defVar(mod, -thUB <= th[i=1:nNode, j=i+1:nNode] <= thUB)
    @defVar(mod, x[i=1:nNode, j=i+1:nNode], Bin)
    @defVar(mod, p[s=1:nSamp])
    @defVar(mod, t[s=1:nSamp])

    @setNLObjective(mod, Min, 1.0/nSamp * sum{t[s], s=1:nSamp}) #optionally use 1.0/nSamp multiplier

    @addNLConstraint(mod, tGE[s=1:nSamp], t[s] >= exp(p[s]))

    @addConstraint(mod, pEq[s=1:nSamp], p[s] == -sum{samps[s,i] * samps[s,j] * th[i,j], i=1:nNode, j=i+1:nNode})

    @addConstraint(mod, deg[k=1:nNode], sum{x[k,j], j=k+1:nNode} + sum{x[i,k], i=1:k-1} <= maxDeg)

    #big-M constraints (is it possible to replace with indicator constraints? pajarito compatibility?)
    @addConstraint(mod, thU[i=1:nNode, j=i+1:nNode], th[i,j] <= thUB * x[i,j])
    @addConstraint(mod, thL[i=1:nNode, j=i+1:nNode], th[i,j] >= -thUB * x[i,j])

    stat = solve(mod)
```

The error only started when I took the exponential cones out of the objective by adding the t variables and the tGE constraints.

**Comment by emreyamangil** [comment]
Woops! I am getting the same thing, looking into it!

**Comment by emreyamangil** [comment]
Chris, I pushed the fix to the current PR to be as fast as possible! @mlubin

**Comment by mlubin** [comment]
@emreyamangil please use separate PRs for separate issues. you can create a new branch off of master to work on multiple PRs in parallel

**Comment by emreyamangil** [comment]
Just wanted to make it as fast as possible (appveyor taking forever, just wanted to get it out of Chris' way before our meeting for tomorrow, sorry!)

**Comment by chriscoey** [comment]
thanks for working hard on this during your evening Emre!

don't need to rush things, I've always got something I can be working on
anyway haha

**Comment by emreyamangil** [comment]
Gaming vs coding, surprisingly today coding wins :)

**Comment by chriscoey** [comment]
got the update, thanks Emre!

since my objective values are so small, might be good to instead print out
the numbers with scientific notation with %e (instead of %f with 2
decimals).

e Scientific notation (mantissa/exponent), lowercase 3.9265e+2
E Scientific notation (mantissa/exponent), uppercase 3.9265E+2

**Comment by chriscoey** [comment]
otherwise, very nice formatting (this is coming from a perfectionist)

**Comment by chriscoey** [comment]
i think we could do 4-6 significant digits in the notation, btw

**Comment by mlubin** [comment]
Always using scientific notation would be annoying for readability. %g might be the right one for this but not sure if it's supported by the ``@printf`` macro

**Comment by chriscoey** [comment]
oh true yeah %g would be nice!

**Comment by emreyamangil** [comment]
I tried %g it works with printf, will do this update right away tomorrow!
