### ISSUE TITLE
move to ConicNonlinearBridge.jl

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#4]
We should remove the ``conic_nlp_wrapper.jl`` code and move to the [https://github.com/mlubin/ConicNonlinearBridge.jl](ConicNonlinearBridge) version. Once ConicNonlinearBridge has all the features we need, I'm planning on moving the code into MathProgBase.

**Comment by emreyamangil** [comment]
Yupp! I will update ConicNonlinearBridge asap!
