### ISSUE TITLE
"UndefVarError: dcp_objval not defined"

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#40]
Just got this error while running (present version of) compare.jl in our dropbox. The file's top matter and the full error message are below. 
```
using ConicNonlinearBridge, Convex, Pajarito, Ipopt
# using Gurobi
using CPLEX

const conic_solver = ConicNLPWrapper(
    nlp_solver=IpoptSolver(print_level=0))

const pajarito_solver = PajaritoSolver(
    algorithm="BC",
    verbose=1,
    socp_disaggregator=true,
    time_limit=60*60*8,
    # mip_solver=GurobiSolver(OutputFlag=1),
    mip_solver=CplexSolver(CPX_PARAM_SCRIND=1,CPX_PARAM_MIPDISPLAY=1,CPX_PARAM_EPINT=1e-8,CPX_PARAM_EPRHS=1e-8,CPX_PARAM_TILIM=60*60*8),
    cont_solver=conic_solver)
```
> LoadError: UndefVarError: dcp_objval not defined
>  in coniccallback at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:921
>  in lazycallback at /Users/chris/.julia/v0.4/JuMP/src/callbacks.jl:65
>  in anonymous at /Users/chris/.julia/v0.4/JuMP/src/callbacks.jl:79
>  in mastercallback at /Users/chris/.julia/v0.4/CPLEX/src/CplexSolverInterface.jl:443
>  [inlined code] from /Users/chris/.julia/v0.4/CPLEX/src/cpx_common.jl:17
>  in optimize! at /Users/chris/.julia/v0.4/CPLEX/src/cpx_solve.jl:2
>  in optimize! at /Users/chris/.julia/v0.4/CPLEX/src/CplexSolverInterface.jl:158
>  in solve at /Users/chris/.julia/v0.4/JuMP/src/solvers.jl:138
>  in optimize! at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:965
>  in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:32
>  in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:13
>  in solveNode at /Users/chris/Dropbox/IsingModels/julia/node.jl:28
>  in matchNodes at /Users/chris/Dropbox/IsingModels/julia/node.jl:83
>  in match at /Users/chris/Dropbox/IsingModels/julia/compare.jl:27
>  in findMinSampSize at /Users/chris/Dropbox/IsingModels/julia/compare.jl:53
>  in include_string at loading.jl:266
>  in include_string at /Users/chris/.julia/v0.4/CodeTools/src/eval.jl:32
>  in anonymous at /Users/chris/.julia/v0.4/Atom/src/eval.jl:84
>  in withpath at /Users/chris/.julia/v0.4/Requires/src/require.jl:37
>  in withpath at /Users/chris/.julia/v0.4/Atom/src/eval.jl:53
>  [inlined code] from /Users/chris/.julia/v0.4/Atom/src/eval.jl:83
>  in anonymous at task.jl:58
> while loading /Users/chris/Dropbox/IsingModels/julia/compare.jl, in expression starting on line 96

**Comment by chriscoey** [comment]
happens rarely, but seemingly totally randomly (same models different data)

**Comment by chriscoey** [comment]
when using compare.jl with graph.jl instead of node.jl (switch boolNode), I get this error half every other run of compare.jl, at the start. So it seems some random data samples cause the error, others don't. Perhaps when something goes wrong numerically, a problem isn't detected?

**Comment by chriscoey** [comment]
OK switching to "OA" because the error is too frequent

**Comment by chriscoey** [comment]
SIGHS. ok two issues which may be related (if not, i'll submit another issue)

1) after switching to OA and running the same code, I got "UndefVarError: dcp_objval not defined" again!

2) the solve was getting stuck in repeating loop. I was seeing the following output just repeat forever with no change in any of the numbers anywhere:
```
Node log . . .
Best integer =   3.110729e-01  Node =       0  Best node =   0.000000e+00

Gomory fractional cuts applied:  7
       31         0.31107           0.31129          0.00021         0.31129
Warning:  Non-integral bounds for integer variables rounded.
6 of 6 MIP starts provided solutions.
MIP start 'm6' defined initial solution with objective 0.3111.
Warning:  Non-integral bounds for integer variables rounded.
Tried aggregator 1 time.
MIP Presolve eliminated 2701 rows and 201 columns.
Reduced MIP has 981 rows, 272 columns, and 5516 nonzeros.
Reduced MIP has 36 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (3.34 ticks)
Probing time = 0.01 sec. (4.70 ticks)
Cover probing fixed 0 vars, tightened 200 bounds.
Tried aggregator 1 time.
MIP Presolve eliminated 441 rows and 98 columns.
Reduced MIP has 540 rows, 174 columns, and 2919 nonzeros.
Reduced MIP has 36 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (1.61 ticks)
Probing time = 0.00 sec. (0.10 ticks)
Tried aggregator 1 time.
Reduced MIP has 540 rows, 174 columns, and 2919 nonzeros.
Reduced MIP has 36 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.82 ticks)
Probing time = 0.00 sec. (0.10 ticks)
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: deterministic, using up to 8 threads.

Node log . . .
Best integer =   3.110729e-01  Node =       0  Best node =   0.000000e+00

Gomory fractional cuts applied:  7
```

**Comment by emreyamangil** [comment]
I may have an idea why this is happening, let me try to make a quick fix (garbage collector maybe doing something funny)

**Comment by chriscoey** [comment]
confirmed fixed
