### ISSUE TITLE
integer solutions cycling

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#42]
So Miles and I just found that the integer solutions are cycling when we run compare.jl in the dropbox with node problem (and also the full graph problem).

We printed them using the following code added to line 988 of conic.jl
   ```
mip_solution = getValue(m.mip_x)
int_indices = [getCategory(Variable(mip_model,i)) != :Cont for i in 1:MathProgBase.numvar(mip_model)]
@show mip_solution[int_indices]
```

This was the output when we set the random seed to 100
> Best integer =   7.257441e-01  Node =       0  Best node =   7.529509e-04
> mip_solution[int_indices] = [1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0]

**Comment by emreyamangil** [comment]
http://www.nooooooooooooooo.com/

Let's work on it today, it means the separation is failing miserably (I am pretty sure by there is a magnitude issue with the cut generated), but BC is working right?

**Comment by emreyamangil** [comment]
So much confusion, it finishes with 500 samples on my end?

**Comment by mlubin** [comment]
Let's add explicit detection for repeated mip solutions and stop when detected.
