### ISSUE TITLE
default solvers

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#45]
Maybe use ``MathProgBase.defaultMIPsolver``, ``MathProgBase.defaultNLPsolver``, and/or ``MathProgBase.defaultConicsolver`` if user does not specify a solver?

**Comment by emreyamangil** [comment]
Awesome! Will do this asap today! Can i combine this with hide conicnonlinearbridge??

**Comment by mlubin** [comment]
Yes, sounds good
