### ISSUE TITLE
rename source files

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#5]
Maybe rename ``pajarito_nlp.jl`` to ``nonlinear.jl`` and ``pajarito_cone_cb.jl`` to ``conic.jl``?

**Comment by emreyamangil** [comment]
Perfect!

**Comment by emreyamangil** [comment]
Btw when I am renaming these I will move the recent pajarito_nlp here just to make sure, seems like I did something over the last month on it!
