### ISSUE TITLE
Allow user to specify warm start

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#55]
Especially through JuMP.

Since gurobi may not use a warm start on the integer variables, solve the LP with warm start variables fixed and pass all variable values to mip solver.

**Comment by emreyamangil** [comment]
Oh god.. feels like 3 centuries ago, will work on it asap!

**Comment by emreyamangil** [comment]
#70 let's you warmstart if you provide a full vector at the moment!
