### ISSUE TITLE
rename socp_disaggregator

### ISSUE THREAD

**Issue by mlubin** [mlubin/Pajarito.jl#65]
to `disaggregate_soc` and set the default to `true`.
https://github.com/mlubin/Pajarito.jl/pull/64

**Comment by emreyamangil** [comment]
Ipopt is crashing on solver test 2 with soc disaggregate, working on figuring this out!

**Comment by mlubin** [comment]
It may be a good idea to turn it off by default if we're using
conicnonlinearbridge.

**Comment by emreyamangil** [comment]
I see, I am working on something at the moment, to round mip_solution's integer components as soon as we get them, what are the chances it is causing numerical issues sometimes??
