### ISSUE TITLE
accidentally ran with no integer constraints, got "LoadError: invalid Array dimensions"

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#79]
maybe you want to throw a different error, or a warning and just solve the continuous problem, when a continuous problem is given to Pajarito
> LoadError: invalid Array dimensions
>  in call at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in preprocessIntegersOut at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:251
>  in loadConicModel at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:509
>  in coniccallback at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:957
>  in optimize! at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:1161
>  in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:32
>  in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:13
>  in dOpt at /Users/chris/Dropbox/misdp/julia/staticExp.jl:51
>  in include_string at loading.jl:266
>  in include_string at /Users/chris/.julia/v0.4/CodeTools/src/eval.jl:32
>  in anonymous at /Users/chris/.julia/v0.4/Atom/src/eval.jl:84
>  in withpath at /Users/chris/.julia/v0.4/Requires/src/require.jl:37
>  in withpath at /Users/chris/.julia/v0.4/Atom/src/eval.jl:53
>  [inlined code] from /Users/chris/.julia/v0.4/Atom/src/eval.jl:83
>  in anonymous at task.jl:58
> while loading /Users/chris/Dropbox/misdp/julia/staticExp.jl, in expression starting on line 113

**Comment by emreyamangil** [comment]
Should we just return an error? I don't like wrapping a continuous solver with unnecessary methods?

**Comment by mlubin** [comment]
No, we should solve the problem! It's a good edge case to test the code.

**Comment by chriscoey** [comment]
Indeed, error is the best way to go because we shouldn't indulge stupidity

**Comment by chriscoey** [comment]
Lol miles and I replied at the same time and disagreed

**Comment by emreyamangil** [comment]
Well, Miles wants it ironclad, we will make it ironclad! :)
