### ISSUE TITLE
error in conic/Mosek

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#81]
I ran the file TEST_contFiniteExp.jl in our dropbox, with the new atom in Convex "sgeomean_eig". got this error:
```
LoadError: Mosek.MosekError(1390,"The lower bound specified is not a number (nan).")
 in putconboundslice at /Users/chris/.julia/v0.4/Mosek/src/msk7_functions.jl:2895
 in loadproblem! at /Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:347
 in loadproblem! at /Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:93
 in loadConicModel at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:516
 in coniccallback at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:968
 in optimize! at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:1172
 in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:32
 in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:13
 in dOpt at /Users/chris/Dropbox/misdp/julia/contFiniteExp.jl:37
 in include_string at loading.jl:266
 in include_string at /Users/chris/.julia/v0.4/CodeTools/src/eval.jl:32
 in anonymous at /Users/chris/.julia/v0.4/Atom/src/eval.jl:84
 in withpath at /Users/chris/.julia/v0.4/Requires/src/require.jl:37
 in withpath at /Users/chris/.julia/v0.4/Atom/src/eval.jl:53
 [inlined code] from /Users/chris/.julia/v0.4/Atom/src/eval.jl:83
 in anonymous at task.jl:58
while loading /Users/chris/Dropbox/misdp/julia/contFiniteExp.jl, in expression starting on line 80
```

**Comment by chriscoey** [comment]
the atom is on the branch https://github.com/JuliaOpt/Convex.jl/blob/nthroot_det/src/atoms/sdp_cone/nthroot_det.jl

**Comment by emreyamangil** [comment]
Woops! I will look into this asap when I get home!

**Comment by chriscoey** [comment]
thanks! here was the output when i tried running with SCS:

> 
> Pajarito started...
> 
> MICONE algorithm OA is chosen.
> MICONE has 46 variables, 52 linear constraints, 3 nonlinear cones.
> Initial objective =      -3.18198.
> 
> Iteration   MIP Objective   Conic Objective   Optimality Gap   Best Solution    Primal Inf.      OA Inf.
> WARNING: Not solved to optimality, status: Unbounded
> WARNING: Unbounded ray not available
> WARNING: Variable value not defined for component of x. Check that the model was properly solved.
> WARNING: Variable value not defined for component of x. Check that the model was properly solved.
> 
> Pajarito finished...
> 
> Status            =         Error.
> Iterations        =             0.
> Total time        =       6.59893 sec.
> MIP total time    =       0.99469 sec.
> CONE total time   =       1.21382 sec.
> 
> WARNING: Problem status Error; solution may be inaccurate.
> 
> D optimal integer-constrained
>   objective -Inf
>   solution
> [NaN
>  NaN
>  NaN
>  NaN
>  NaN

**Comment by mlubin** [comment]
Does the continuous problem solve with mosek? Might not be a pajarito issue

**Comment by chriscoey** [comment]
the continuous problem does solve, and the new atom gives the same answer as log_det does, for both SCS and Mosek.

**Comment by chriscoey** [comment]
the answer is correct, according to Boyd

**Comment by emreyamangil** [comment]
Where is this coming from??
WARNING: Not solved to optimality, status: Unbounded

from mip_model (better not as ini_conic_model is bounded) or conic_model? I need to fix this verbosity issue asap!

**Comment by emreyamangil** [comment]
I think its coming from mip_model as its complaining about querying x, which is in the mip_model.

**Comment by chriscoey** [comment]
in fact, all of the continuous solutions are correct, according to Boyd

**Comment by chriscoey** [comment]
for integer constrained problems, full output is

> ****D optimal****
> 
> 
> Pajarito started...
> 
> MICONE algorithm OA is chosen.
> MICONE has 46 variables, 52 linear constraints, 3 nonlinear cones.
> Initial objective =      -3.18198.
> 
> Iteration   MIP Objective   Conic Objective   Optimality Gap   Best Solution    Primal Inf.      OA Inf.
> WARNING: Not solved to optimality, status: Unbounded
> WARNING: Unbounded ray not available
> WARNING: Variable value not defined for component of x. Check that the model was properly solved.
> WARNING: Variable value not defined for component of x. Check that the model was properly solved.
> 
> Pajarito finished...
> 
> Status            =         Error.
> Iterations        =             0.
> Total time        =       0.83232 sec.
> MIP total time    =       0.00091 sec.
> CONE total time   =       0.82904 sec.
> 
>   objective -Inf
>   solution
> [NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN]
> 
> 
> ****A optimal****
> 
> WARNING: Problem status Error; solution may be inaccurate.
> 
> Pajarito started...
> 
> MICONE algorithm OA is chosen.
> MICONE has 35 variables, 40 linear constraints, 2 nonlinear cones.
> Initial objective =       0.84953.
> 
> Iteration   MIP Objective   Conic Objective   Optimality Gap   Best Solution    Primal Inf.      OA Inf.
> 
> Pajarito finished...
> 
> Status            =         Error.
> Iterations        =             0.
> Total time        =       0.73669 sec.
> MIP total time    =       0.00125 sec.
> CONE total time   =       0.72417 sec.
> 
>   objective Inf
>   solution
> [NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN
>  NaN]
> 
> 
> ****E optimal****
> 
> WARNING: Problem status Error; solution may be inaccurate.
> 
> Pajarito started...
> 
> MICONE algorithm OA is chosen.
> MICONE has 25 variables, 26 linear constraints, 1 nonlinear cones.
> Initial objective =      -1.80000.
> 
> Iteration   MIP Objective   Conic Objective   Optimality Gap   Best Solution    Primal Inf.      OA Inf.
>         0   -2.2500000e+00   +1.7127370e-07   +2.2500002e+00   +1.7127370e-07   -1.0000000e+05   -0.0000000e+00
>         1   -2.2500000e+00   +1.7127370e-07   +2.2500002e+00   +1.7127370e-07   -1.0000000e+05   +0.0000000e+00
> 
> Pajarito finished...
> 
> Status            =    Suboptimal.
> Iterations        =             1.
> Total time        =       0.00650 sec.
> MIP total time    =       0.00178 sec.
> CONE total time   =       0.00183 sec.
> 
>   objective -1.7127370411515208e-7
>   solution
> [0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  -0.0
>  -0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  5.0]
> WARNING: Mixed-integer cycling detected, terminating Pajarito...
> WARNING: Problem status Suboptimal; solution may be inaccurate.

**Comment by emreyamangil** [comment]
Looking into it! (something is fishy, for E-optimal mip_objval < ini_conic_objval)

**Comment by emreyamangil** [comment]
Yupp as suspected, CPLEX returns dual infeasible in the first iteration, so there must be an issue with initial cut generation, looking into it

**Comment by emreyamangil** [comment]
primal cuts also return the same thing, hmmm..

**Comment by mlubin** [comment]
What does primal cuts mean with SDP?

**Comment by emreyamangil** [comment]
Woops you won't like the solution, quick phone chat??

**Comment by chriscoey** [comment]
I'm down. Miles?

**Comment by emreyamangil** [comment]
pushing the fix soon!!

**Comment by chriscoey** [comment]
hmmm I'm still getting the error after pulling

**Comment by chriscoey** [comment]
oops the option hold on

**Comment by chriscoey** [comment]
****D optimal****

MOSEK warning 705: 1 near zero elements are specified in sparse row ''(10)
of matrix 'A'.
MOSEK warning 705: 2 near zero elements are specified in sparse row ''(11)
of matrix 'A'.
MOSEK warning 705: 1 near zero elements are specified in sparse row ''(12)
of matrix 'A'.
MOSEK warning 705: 7 near zero elements are specified in sparse row ''(13)
of matrix 'A'.
MOSEK warning 705: 1 near zero elements are specified in sparse row ''(21)
of matrix 'A'.
MOSEK warning 705: 2 near zero elements are specified in sparse row ''(22)
of matrix 'A'.

Pajarito started...

MICONE algorithm OA is chosen.
MICONE has 46 variables, 52 linear constraints, 3 nonlinear cones.
Initial objective =      -3.18198.

Iteration   MIP Objective   Conic Objective   Optimality Gap   Best
Solution    Primal Inf.      OA Inf.
        0   -3.1819805e+00   -6.1164228e-04   +3.1813688e+00
-6.1164228e-04   +1.4248034e+00   +3.1814903e+00
        1   -3.0228845e+00   -1.8000000e+00   +1.2228845e+00
-1.8000000e+00   +5.4873442e-01   +6.7566917e-01
        2   -2.7046924e+00   -2.2045408e+00   +5.0015169e-01
-2.2045408e+00   +1.6281375e-01   +8.1287180e-01
        3   -2.2273843e+00   -2.2045408e+00   +2.2843557e-02
-2.2045408e+00   +3.2058408e-02   +2.2843560e-02
        4   -2.2045408e+00   -2.2045408e+00   -3.3234082e-10
-2.2045408e+00   -3.3128869e-09   +0.0000000e+00

Pajarito finished...

Status            =       Optimal.
Optimum objective =      -2.20454.
Iterations        =             4.
Total time        =       0.04023 sec.
MIP total time    =       0.00756 sec.
CONE total time   =       0.02710 sec.

  objective 2.20454076572919
  solution
[0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 3.0
 -0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 2.0]


****A optimal****

MOSEK warning 705: 1 near zero elements are specified in sparse row ''(22)
of matrix 'A'.
MOSEK warning 705: 2 near zero elements are specified in sparse row ''(23)
of matrix 'A'.
MOSEK warning 705: 1 near zero elements are specified in sparse row ''(25)
of matrix 'A'.
MOSEK warning 705: 7 near zero elements are specified in sparse row ''(28)
of matrix 'A'.
MOSEK warning 705: 1 near zero elements are specified in sparse row ''(31)
of matrix 'A'.
MOSEK warning 705: 2 near zero elements are specified in sparse row ''(32)
of matrix 'A'.

Pajarito started...

MICONE algorithm OA is chosen.
MICONE has 35 variables, 40 linear constraints, 2 nonlinear cones.
Initial objective =       0.84953.

Iteration   MIP Objective   Conic Objective   Optimality Gap   Best
Solution    Primal Inf.      OA Inf.
        0   +8.4952793e-01   +2.3611111e+00   +1.5115832e+00
+2.3611111e+00   -1.0000000e+05   +1.3967565e+00
        1   +8.4952793e-01   +1.0185185e+00   +1.6899059e-01
+1.0185185e+00   -1.0000000e+05   +1.3009478e-01
        2   +9.1983497e-01   +1.1111111e+00   +9.8683544e-02
+1.0185185e+00   -1.0000000e+05   +1.3895665e-01
        3   +1.0185185e+00   +1.0185185e+00   +3.7905525e-09
+1.0185185e+00   -1.0000000e+05   +0.0000000e+00

Pajarito finished...

Status            =       Optimal.
Optimum objective =       1.01852.
Iterations        =             3.
Total time        =       0.02520 sec.
MIP total time    =       0.00525 sec.
CONE total time   =       0.01590 sec.

  objective 1.0185185141489113
  solution
[0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 2.0
 -0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 3.0]


****E optimal****

MOSEK warning 705: 1 near zero elements are specified in sparse row ''(22)
of matrix 'A'.
MOSEK warning 705: 2 near zero elements are specified in sparse row ''(23)
of matrix 'A'.
MOSEK warning 705: 1 near zero elements are specified in sparse row ''(24)
of matrix 'A'.
MOSEK warning 705: 7 near zero elements are specified in sparse row ''(25)
of matrix 'A'.

Pajarito started...

MICONE algorithm OA is chosen.
MICONE has 25 variables, 26 linear constraints, 1 nonlinear cones.
Initial objective =      -1.80000.

Iteration   MIP Objective   Conic Objective   Optimality Gap   Best
Solution    Primal Inf.      OA Inf.
        0   -1.8000000e+00   +1.9904046e-09   +1.8000000e+00
+1.9904046e-09   -1.0000000e+05   +1.8000000e+00
        1   -1.8000000e+00   -1.8000000e+00   +2.6297468e-08
-1.8000000e+00   -1.0000000e+05   +0.0000000e+00

Pajarito finished...

Status            =       Optimal.
Optimum objective =      -1.80000.
Iterations        =             1.
Total time        =       0.00908 sec.
MIP total time    =       0.00180 sec.
CONE total time   =       0.00505 sec.

  objective 1.799999973702532
  solution
[0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0
 -0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 4.0]

**Comment by emreyamangil** [comment]
Yupp exactly what I am getting! Does the objective make sense??

**Comment by chriscoey** [comment]
solutions/objective aren't *crazy*
a little different from the continuous ones but not too much
how the heck do we verify that it's correct? does YALMIP do MISDP?

**Comment by mlubin** [comment]
Yes, should compare with YALMIP

**Comment by mlubin** [comment]
Or, for small problems, enumerate all possible integer assignments

**Comment by chriscoey** [comment]
ok yalmip it is

**Comment by chriscoey** [comment]
may need to start booking that p=np vacation guys

**Comment by emreyamangil** [comment]
Mid july, though i just want april to be over!! P=np at the end of april!!😁

**Comment by chriscoey** [comment]
hmmm minor unexpected issues. so i figure that as nExp get big (like, 500,
which i just tried), the integer solutions should approach the continuous
ones

on E optimal, they do, perfectly

on A optimal, we get NaNs for nExp >= 15 or so

on D optimal, the solutions are split on different nodes even for nExp=500

**Comment by emreyamangil** [comment]
I wonder if we are running into duality gap issues on A optimal??

**Comment by chriscoey** [comment]
So why does A optimal fail for fairly small nExp but others don't

The D-optimal solution isn't necessarily a problem, because it places
weights on 2 of the 3 nodes you'd only ever want to use, though they're a
different 2 from what the continuous problem said. but 500 is large, it
should be approaching cont solution

these are the optimal continuous sols for same data. not in order:

[image: Inline image 1]

**Comment by emreyamangil** [comment]
Yupp its still duality gap on A, very curious why on A...

**Comment by chriscoey** [comment]
so if I set the dual_cut_zero_tol smaller than 1e-9, I get the same error

LoadError: Mosek.MosekError(1390,"The lower bound specified is not a number
(nan).")
in putconboundslice at
/Users/chris/.julia/v0.4/Mosek/src/msk7_functions.jl:2895
in loadproblem! at
/Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:347
in loadproblem! at
/Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:93
in loadConicModel at /Users/chris/.julia/v0.4/Pajarito/src/conic.jl:518

is that OK, or do we want to warn people?

**Comment by chriscoey** [comment]
might be the duality gap rearing its ugly head

**Comment by chriscoey** [comment]
ah ok. hmmm well. better postpone those vacation plans

and even for nExp=2000, I'm still getting the integer solution for D is
different set of points from the continuous one

**Comment by emreyamangil** [comment]
Well, as long as lower bound meets upper bound at termination, I would prefer trusting the SDP solver at that point, though definitely something might be fishy. We should definitely handle Unknown status better, but identifying when duality gap happens might be tricky (MOSEK doesn't return anything except for Unknown status in this case)

**Comment by emreyamangil** [comment]
Yupp, travel plans are out the window for now, until we fix this!

**Comment by mlubin** [comment]
Unknown status means we stop and report solver failure

**Comment by emreyamangil** [comment]
Yupp thats what we are doing right now!

**Comment by mlubin** [comment]
So what's the problem?

**Comment by emreyamangil** [comment]
It would have been nice if we could somehow verify duality fails, though we can't at the moment!

**Comment by chriscoey** [comment]
so I still don't know why no matter how large I make nExp, the solution
doesn't match for D optimal. but whatever.

now we need to solve strong duality issue to get E optimal working

**Comment by emreyamangil** [comment]
A optimal you mean right?? E works on me!

**Comment by emreyamangil** [comment]
Well, at least we get 1 problem working per day, 1ppd, that's progress!!

**Comment by chriscoey** [comment]
guys, maybe we could have a quick chat tomorrow sometime after Miles' talk.
that way we could make more progress before our longer wednesday meeting.
eg we could discuss how to make the bounds idea that JP says should be fine
work, and try to code a small example and talk about it on wednesday

tonight i'm coding up a primal continuous sdp column generation algorithm
based on the latex file Emre worked on

**Comment by emreyamangil** [comment]
Good for me! I just have a meeting at 11am with Russell!

**Comment by chriscoey** [comment]
yes i meant A optimal haha. E always has worked well

**Comment by mlubin** [comment]
@chriscoey, to get stated on the bounding idea, you could work on writing up the model as an explicit MISDP in JuMP to give us control over the conic formulation

**Comment by chriscoey** [comment]
but we need convex.jl to reformulate automatically right? because the
objective atoms require some of that. or do you want me to mimic what
convex.jl does internally?

**Comment by chriscoey** [comment]
are you able to plug convex.jl into jump like you did with jugp?

**Comment by emreyamangil** [comment]
We can manually lift to MISDP and use ConicModel from MathProgBase (I think what Miles means)

**Comment by mlubin** [comment]
You'll need to manually replicate the reformulations that Convex.jl does

**Comment by chriscoey** [comment]
OK, I don't fully understand why we can't use convex.jl. let's have a
conversation when Miles is free about what control we need over the conic
model, what we need to do with bounds etc

**Comment by chriscoey** [comment]
I put a file called SDPConstraintGen into the misdp julia folder

I can't figure out how to fix the "NoSign" error convex.jl is giving. it is
coming from the RSOC constraint in line 74 I believe. maybe it's worried
the terms on the RHS of the RSOC constraint aren't necessarily nonnegative?

LoadError: MethodError: `+` has no method matching +(::Convex.NoSign)
Closest candidates are:
+(::Convex.NoSign, !Matched::Convex.NoSign)
+(::Convex.NoSign, !Matched::Convex.Sign)
+(::Convex.Sign, !Matched::Convex.NoSign)
...
in sum at tuple.jl:133
in sign at /Users/chris/.julia/v0.4/Convex/src/atoms/affine/stack.jl:26
in sign at /Users/chris/.julia/v0.4/Convex/src/atoms/affine/transpose.jl:25
(repeats 2 times)
in map at tuple.jl:61
in sign at /Users/chris/.julia/v0.4/Convex/src/atoms/affine/stack.jl:26
in sign at /Users/chris/.julia/v0.4/Convex/src/atoms/affine/transpose.jl:25
in vexity at /Users/chris/.julia/v0.4/Convex/src/expressions.jl:63
in vexity at
/Users/chris/.julia/v0.4/Convex/src/constraints/constraints.jl:77
in vexity at /Users/chris/.julia/v0.4/Convex/src/problems.jl:77
in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:20
in solve! at /Users/chris/.julia/v0.4/Convex/src/solution.jl:13
in solveSDPOuterApprox at /Users/chris/misdp/julia/colGenHighDim.jl:92
in include_string at loading.jl:266
in include_string at /Users/chris/.julia/v0.4/CodeTools/src/eval.jl:32
in anonymous at /Users/chris/.julia/v0.4/Atom/src/eval.jl:84
in withpath at /Users/chris/.julia/v0.4/Requires/src/require.jl:37
in withpath at /Users/chris/.julia/v0.4/Atom/src/eval.jl:53
[inlined code] from /Users/chris/.julia/v0.4/Atom/src/eval.jl:83
in anonymous at task.jl:58
while loading /Users/chris/misdp/julia/colGenHighDim.jl, in expression
starting on line 108
