### ISSUE TITLE
Add SOC disaggregation for new rotated SOCs

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#84]

**Comment by emreyamangil** [comment]
Weekend project!!

**Comment by chriscoey** [comment]
also note that num_soc_cones and dim_soc_cones are not counting :SOCRotated yet

**Comment by emreyamangil** [comment]
Hmm this won't be trivial, we can certainly use the existing infrastructure to do disaggregation of rotated SOCs, though something might break, I would add new fields instead, I am postponing this a little bit as we don't need this urgently at the moment!

**Comment by chriscoey** [comment]
done in new code

**Comment by emreyamangil** [comment]
Awesome stuff, thanks Chris!

**Comment by emreyamangil** [comment]
Looking forward to your PR!
