### ISSUE TITLE
not doing SOC disagg when using NLP solver

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#87]
changing all the code now so don't do anything just yet

**Comment by emreyamangil** [comment]
You mean "not doing SOC disagg by **default** when using NLP solver"??

**Comment by mlubin** [comment]
The code [here](https://github.com/mlubin/Pajarito.jl/blob/fa8d5a8ce8c84741d02eaf59ebac2bce54c4d3bd/src/conic.jl#L119) is just for the default case. If you explicitly specify ``disaggregate_soc=true`` then it will always do disaggregation.
