### ISSUE TITLE
count number of each type of cone

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#88]
and fix "problem type" at the same time. I got rid of it because it was hopeless.

print under "pajarito started" a table of the number of each type of cone, dimension etc

**Comment by emreyamangil** [comment]
Will do, this doesn't effect much, problem_type is from initial experiment to classify MINLPLIB2 problems, it should go away anyways!

**Comment by emreyamangil** [comment]
Oh Chris I didn't read the second sentence :) Are you working on this already?

**Comment by chriscoey** [comment]
I can do it yeah

**Comment by emreyamangil** [comment]
You got it!!

**Comment by chriscoey** [comment]
done in new code
