### ISSUE TITLE
standardize timing

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#89]
what are all the things we want timed? 

I'm guessing
- cumulative mip time
- cumulative continuous solve time (incl initial solve)
- preprocessing integers
- removing rows
- loading - just MPB.loadproblem?

**Comment by mlubin** [comment]
As far as users should care, the things we want timed are:
- cumulative MIP time
- cumulative continuous solve time
- anything else 

The "anything else" is a measure of the overhead of Pajarito, and users should complain if it's too large relative to the other times. For development purposes it's helpful for us to break the "anything else" into smaller parts like preprocessing, removing rows, loadproblem, etc, but these aren't really user facing.

**Comment by emreyamangil** [comment]
yupp this is all there already!

```
    cputime_mip = 0.0
    cputime_conic = 0.0
    cputime_load = 0.0

    m.prep_timer = 0.0
    m.remove_timer = 0.0
    m.nlp_load_timer = 0.0
```

is there something else that needs timing?

**Comment by chriscoey** [comment]
is there a good reason why the latter timers are fields of m, whereas the former are on their own? can i just make them all m.something_timer?

**Comment by emreyamangil** [comment]
No need to add unnecessary fields to model object. I made them fields of m so that they would go around the code easier that's it (we should remove them and push it around the code if possible).

**Comment by chriscoey** [comment]
ok so you think none of the timers should be fields of m? Miles do you agree?

**Comment by mlubin** [comment]
Depends on how ugly the resulting code would be.

**Comment by emreyamangil** [comment]
That's why I kept the ones under m, let's just leave it as is now, I am closing the issue.

**Comment by chriscoey** [comment]
i'm finding it confusing having some as fields and some not, so I'm trying them all not fields for now, it shouldn't require much passing around

**Comment by emreyamangil** [comment]
Yupp, give it a shot let's see how it looks

**Comment by mlubin** [comment]
PRs welcome :)

**Comment by mlubin** [comment]
Keep it on a separate branch from the SDP stuff
