### ISSUE TITLE
make disaggregate_soc a bool not a symbol

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#90]
and rename it if it doesn't make sense. in the original code, it seems a name like disagg_soc_if_conic would make more sense, if I understood it correctly

**Comment by emreyamangil** [comment]
We did it this way for default value.

**Comment by emreyamangil** [comment]
its actually neat, user inputs a bool but it is cast into a symbol for having a third state that is default.

**Comment by emreyamangil** [comment]
Closing this issue because this was intended!

**Comment by emreyamangil** [comment]
Made it an enum, lemme know if this is better Chris!

**Comment by emreyamangil** [comment]
(But the user is interacting with a bool)
