### ISSUE TITLE
heuristic/warm-start solutions may be infeasible

### ISSUE THREAD

**Issue by chriscoey** [mlubin/Pajarito.jl#95]
if a solver tells us that a warm-start or heuristic solution is infeasible, we should fix that. 

there could be a bug in the feasible solution construction code. or if the issue is that conic solutions are epsilon infeasible, we could use primal cone projections to recover a feasible solution (using some of the same code as dual cone projections)

**Comment by mlubin** [comment]
Something's broken with the MIP warmstarts:
```
WARNING: Ignoring partial starting solution. Cbc requires a feasible value to be specified for all variables.
```
That means Pajarito isn't giving Cbc a complete vector.

**Comment by chriscoey** [comment]
Is it possible to get that message if you give a full vector that's
infeasible? Or are the dimensions necessarily wrong?

**Comment by mlubin** [comment]
@chriscoey, means there are NaNs in the starting point: https://github.com/JuliaOpt/Cbc.jl/blob/456175aa56d087e975805ef0eed82569f6659e8a/src/CbcSolverInterface.jl#L176

**Comment by chriscoey** [comment]
ah ok. i expected there to be bugs in the warm starts. will work on it soon

**Comment by mlubin** [comment]
Could be worth adding an option on whether to pass a solution to the MIP solver. This way we can run an experiment and measure how much it actually helps.

**Comment by chriscoey** [comment]
ok for this remember we need to be looking at the output of the solvers on larger problems to make sure the heuristic solutions work

**Comment by chriscoey** [comment]
ok often we are getting MIP solver readouts like
`MIP start violates constraint R67010 by 0.00
`
in one case I saw the violation was 0.08

so there must be a bug in the solution construction

**Comment by chriscoey** [comment]
OK so now I'm printing MIP solver output on the tests. On "solver test 2":
`MIP start violates constraint R8 by 1.00`
Hopefully that will help me diagnose the issue.

**Comment by mlubin** [comment]
That's a big violation

**Comment by chriscoey** [comment]
Yup, should have been looking at MIP printout earlier

**Comment by chriscoey** [comment]
actually, my mistake, that was simply because I was setting start = 0 so i could calculate initial cut infeas the easy way. I no longer set start on variables initially, and don't try calculating cut infeas the first time.

that means I no longer get any mip start violations from the test set

**Comment by mlubin** [comment]
Did that also resolve the 0.00 violations?

**Comment by chriscoey** [comment]
but that's not good. I'm still getting it on the large problems. mostly 0.00, but I just found one with `MIP start violates constraint R42002 by 0.02`

**Comment by chriscoey** [comment]
so I don't have an easy way to figure out what the bug is

**Comment by mlubin** [comment]
figure out which constraint is R42002

**Comment by chriscoey** [comment]
can I get gurobi to tell me?

**Comment by mlubin** [comment]
no, find out which constraint in JuMP has index 42002

**Comment by mlubin** [comment]
or 42003 if gurobi is zero-based

**Comment by chriscoey** [comment]
@mlubin so the only constraints that are violated by mip starts are cuts that were added at the end of the previous iteration. 

could gurobi be referring to an old MIP start? or is it necessarily referring to the one that I passed in with JuMP most recently?

**Comment by chriscoey** [comment]
from gurobi: "If the Gurobi MIP solver log indicates that your MIP start didn't produce a new incumbent solution, note that there can be multiple explanations. One possibility is that your MIP start is infeasible. Another, more common possibility is that one of the Gurobi heuristics found a solution that is as good as the solution produced by the MIP start, so the MIP start solution was cut off. "

**Comment by chriscoey** [comment]
why would it say both of the following:
```
MIP start did not produce a new incumbent solution
MIP start violates constraint R882 by 0.02
```
If there is one MIP start, it wouldn't check to see if it is incumbent if it is infeasible, right?

Could that suggest that there are multiple MIP starts and it's not talking about the one passed in by JuMP?

**Comment by mlubin** [comment]
Does gurobi start out with a solution that matches the objective value of the MIP start we're giving it?

**Comment by chriscoey** [comment]
the original code wasn't handling heuristics/warm-starts properly. glad we caught this. see PR #125

**Comment by chriscoey** [comment]
haven't seen any issue here on the examples i've been running. so I'm going to close. reopen if solver says mip start is infeasible
