### ISSUE TITLE
using via JuMP

### ISSUE THREAD

**Issue by samiit** [mlubin/Pajarito.jl#97]
Thanks to all the very active developers who are gifting us with such valuable resources for free. I was motivated to it by watching Miles' presentation on AIChE webinar.

I've started to experiment a bit with Pajarito and was solving a simple ILP problem. I'm not sure but I can imagine that Pajarito might be an overkill for this task, but would like your feedback, especially for large problems (around 4 million variables and 4000 constraints; very sparse). Commercial options are not on table for me now!

Besides, since I got familiar with JuMP, I tried to use Parajito within this modelling framework.
But when I do 
```
status = solve(m)
```
it gives an error:

```
MethodError: `LinearQuadraticModel` has no method matching LinearQuadraticModel(::Pajarito.PajaritoSolver)
 in build at /home/sam/.julia/v0.4/JuMP/src/solvers.jl:371
 in solve at /home/sam/.julia/v0.4/JuMP/src/solvers.jl:131
 in include_string at /home/sam/.julia/v0.4/CodeTools/src/eval.jl:28
 in include_string at /home/sam/.julia/v0.4/CodeTools/src/eval.jl:32
 [inlined code] from /home/sam/.julia/v0.4/Atom/src/eval.jl:39
 in anonymous at /home/sam/.julia/v0.4/Atom/src/eval.jl:62
 in withpath at /home/sam/.julia/v0.4/Requires/src/require.jl:37
 in withpath at /home/sam/.julia/v0.4/Atom/src/eval.jl:53
 [inlined code] from /home/sam/.julia/v0.4/Atom/src/eval.jl:61
 in anonymous at task.jl:58
```

The solver was initiated as:
```
algorithm = "OA"
mip_solver = CbcSolver()
nlp_solver = IpoptSolver(print_level=0)
s =PajaritoSolver(algorithm=algorithm,mip_solver=mip_solver,cont_solver=nlp_solver)
m = Model(solver=s)

```
Any suggestions?

Thanks,
Sam

**Comment by mlubin** [comment]
If your problem is an ILP (with no nonlinear constraints), then there's no reason to use Pajarito; you should use Cbc directly. If you have convex quadratic constraints, in order to use Pajarito properly you need to reformulate them into second-order cone form. Convex.jl does this automatically for you, which is why we generally recommend Convex.jl for modeling when using Pajarito.
